import { Card, Class, Monster, OnAttackEffect, OnDeadEffect, OnDefenseEffect, ActiveSkill, GameState } from '@/types/game';

// Base card pool (40 cards)
export const cardPool: Card[] = [
  {
    id: 1,
    name: "Fire Dragon",
    attack: 8,
    health: 6,
    maxPerSession: 2,
    class: [Class.FIRE],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.EXPLODE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 2,
    name: "Earth Golem",
    attack: 4,
    health: 10,
    maxPerSession: 3,
    class: [Class.EARTH],
    staminaCost: 2,
    onAttackEffect: OnAttackEffect.NONE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 3,
    name: "Water Elemental",
    attack: 6,
    health: 6,
    maxPerSession: 2,
    class: [Class.WATER],
    staminaCost: 2,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 4,
    name: "Metal Knight",
    attack: 7,
    health: 8,
    maxPerSession: 2,
    class: [Class.METAL],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 5,
    name: "Wood Elf",
    attack: 5,
    health: 4,
    maxPerSession: 3,
    class: [Class.WOOD],
    staminaCost: 1,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 6,
    name: "Flame Assassin",
    attack: 9,
    health: 4,
    maxPerSession: 2,
    class: [Class.FIRE],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.SACRIFICE,
  },
  {
    id: 7,
    name: "Stone Guardian",
    attack: 3,
    health: 12,
    maxPerSession: 2,
    class: [Class.EARTH],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.NONE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 8,
    name: "Water Healer",
    attack: 4,
    health: 6,
    maxPerSession: 2,
    class: [Class.WATER],
    staminaCost: 2,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 9,
    name: "Metal Berserker",
    attack: 8,
    health: 5,
    maxPerSession: 2,
    class: [Class.METAL],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.EXPLODE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.SACRIFICE,
  },
  {
    id: 10,
    name: "Forest Druid",
    attack: 5,
    health: 7,
    maxPerSession: 2,
    class: [Class.WOOD],
    staminaCost: 2,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 11,
    name: "Volcanic Giant",
    attack: 10,
    health: 8,
    maxPerSession: 1,
    class: [Class.FIRE, Class.EARTH],
    staminaCost: 4,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.EXPLODE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 12,
    name: "Storm Mage",
    attack: 7,
    health: 5,
    maxPerSession: 2,
    class: [Class.WATER, Class.METAL],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 13,
    name: "Nature's Warden",
    attack: 6,
    health: 8,
    maxPerSession: 2,
    class: [Class.WOOD, Class.EARTH],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 14,
    name: "Blade Master",
    attack: 8,
    health: 6,
    maxPerSession: 2,
    class: [Class.METAL],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.SACRIFICE,
  },
  {
    id: 15,
    name: "Ancient Treant",
    attack: 4,
    health: 12,
    maxPerSession: 1,
    class: [Class.WOOD],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.NONE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 16,
    name: "Phoenix Warrior",
    attack: 7,
    health: 5,
    maxPerSession: 2,
    class: [Class.FIRE],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.EXPLODE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 17,
    name: "Crystal Golem",
    attack: 5,
    health: 9,
    maxPerSession: 2,
    class: [Class.EARTH, Class.METAL],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.NONE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 18,
    name: "Tide Caller",
    attack: 6,
    health: 6,
    maxPerSession: 2,
    class: [Class.WATER],
    staminaCost: 2,
    onAttackEffect: OnAttackEffect.LIFESTEAL,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 19,
    name: "Steel Sentinel",
    attack: 6,
    health: 8,
    maxPerSession: 2,
    class: [Class.METAL],
    staminaCost: 3,
    onAttackEffect: OnAttackEffect.NONE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.THORNS,
    activeSkill: ActiveSkill.NONE,
  },
  {
    id: 20,
    name: "Forest Scout",
    attack: 4,
    health: 4,
    maxPerSession: 3,
    class: [Class.WOOD],
    staminaCost: 1,
    onAttackEffect: OnAttackEffect.CRITICAL_STRIKE,
    onDeadEffect: OnDeadEffect.NONE,
    onDefenseEffect: OnDefenseEffect.NONE,
    activeSkill: ActiveSkill.NONE,
  }
];

export const monsters: Monster[] = [
  {
    id: 1,
    health: 40,
    attack: 5,
    class: [Class.FIRE, Class.EARTH],
  },
  {
    id: 2,
    health: 50,
    attack: 6,
    class: [Class.WATER, Class.METAL],
  },
  {
    id: 3,
    health: 60,
    attack: 7,
    class: [Class.WOOD, Class.FIRE],
  },
];

export const mockGameState: GameState = {
  _id: "mock-game-1",
  playerId: "player-1",
  sessionId: "session-1",
  currentStage: 1,
  playerHealth: 40,
  playerStamina: 1,
  deck: [],
  currentMonster: {
    monsterId: 1,
    health: 40,
    attack: 5,
  },
  cardsOnField: [],
  battleHistory: [],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};